---
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binary
        run: go build
      - name: Run tests
        run: go test -v ./...
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install cram
        run: pip install cram --user
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build binary
        run: go build
      - name: Run tests
        run: PATH=$PWD:$PATH cram -v tests/*.t
